name: HaxRDP

on: [push, workflow_dispatch]

jobs:
  build:
 
    runs-on:  Windows-Intest

    steps:
    - name:  DOWNLOADING
      run:  Invoke-WenRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-
amd64.zip-OutFile ngrok.zip
    - name: EXTRACT
      run: Expand-Archive ngrok.zip
    - name: AUTENTIFIKASI
      run: .\ngrok\ngrok.exe authtoken your_authtoken
    - name  ENABLE  TS
      run:  set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal 
Server'-name  "fDenyTSConnections" -Value 0
    - run:  Enable-NetFirewallRule  -DisplayGroup  "Remote Desktop"
    - run:  Set-ItemProperty -Path  'HKLM:\System\CurrentControlSet\Control\Terminal
Server\WinStations\RDP-Top'  -name  "UserAuthentication"  -Value  1
    - run:  Set-LocalUser  -Name  "runneradmin"  -password  (ConvertTo-SecureString -
AsPlainText  "P@ssword!"  -Force)
    - name:  DONE!
      run:  .\ngrok\ngrok.exe tcp 3389
